name: Test

on:
  pull_request:
    branches:
      - main
      - staging
      - dev
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test
